export interface PlayerModel {
    auth: string;
    conn: string;
    name: string;
    rating: number;
    totals: number;
    disconns: number;
    wins: number;
    loses: number;
    goals: number;
    assists: number;
    ogs: number;
    losePoints: number;
    balltouch: number;
    passed: number;
    mute: boolean;
    muteExpire: number;
    rejoinCount: number;
    superadmin: boolean;
    role: string;
    roleExpire: number | null;
    joinDate: number;
    leftDate: number;
    malActCount: number;
    gk: number;
    goalsAgainstGk: number;
    hatTricks: number;
    perfectGk: number;
    username: string | null;
    password: string | null;
    warningCount: number;

    goalsPlusAssistsPerGame: number;
    goalsPerGame: number;
    goalsAgainstPerGame: number;
    oGsPerGame: number;
    assistsPerGame: number;
    winrate: number;
    passPercentage: number;
}