import { stadiumInfo } from "./stadiumInfo";

export const stadium: stadiumInfo = {
    name: "3v3",
    minPlayers: 5,
    maxPlayers: 6,
    stadiumText: `
    {
        "name":"SINDICATO THREE",
        "width":648,
        "height":270,
        "bg":{
            "type":"",
            "color":"2a3a40",
            "width":0,
            "height":0
        },
        "vertexes":[
            /* 0 */{
                "x":550,
                "y":240,
                "cMask":[
                    "ball"
                ]
            },
            /* 1 */{
                "x":550,
                "y":-240,
                "cMask":[
                    "ball"
                ]
            },
            /* 2 */{
                "x":0,
                "y":270,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            /* 3 */{
                "x":0,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"a3acc2"
            },
            /* 4 */{
                "x":0,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"a3acc2"
            },
            /* 5 */{
                "x":0,
                "y":-270,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            /* 6 */{
                "x":-550,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 7 */{
                "x":-590,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 8 */{
                "x":-590,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 9 */{
                "x":-550,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 10 */{
                "x":550,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 11 */{
                "x":590,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 12 */{
                "x":590,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 13 */{
                "x":550,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 14 */{
                "x":-550,
                "y":80,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 15 */{
                "x":-550,
                "y":240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 16 */{
                "x":-550,
                "y":-80,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 17 */{
                "x":-550,
                "y":-240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 18 */{
                "x":-550,
                "y":240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 19 */{
                "x":550,
                "y":240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 20 */{
                "x":550,
                "y":80,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 21 */{
                "x":550,
                "y":240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 22 */{
                "x":550,
                "y":-240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 23 */{
                "x":550,
                "y":-80,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 24 */{
                "x":550,
                "y":-240,
                "bCoef":0,
                "cMask":[
                    "ball"
                ]
            },
            /* 25 */{
                "x":550,
                "y":-240,
                "bCoef":0,
                "cMask":[
                    "ball"
                ]
            },
            /* 26 */{
                "x":-550,
                "y":-240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 27 */{
                "x":550,
                "y":-240,
                "cMask":[
                    "ball"
                ],
                "color":"a3acc2"
            },
            /* 28 */{
                "x":0,
                "y":-240,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"a3acc2"
            },
            /* 29 */{
                "x":0,
                "y":-82,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"a3acc2"
            },
            /* 30 */{
                "x":0,
                "y":82,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"a3acc2"
            },
            /* 31 */{
                "x":0,
                "y":240,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"a3acc2"
            },
            /* 32 */{
                "x":0,
                "y":-82,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 33 */{
                "x":0,
                "y":82,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            /* 34 */{
                "x":0,
                "y":82,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            /* 35 */{
                "x":0,
                "y":-82,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 36 */{
                "x":0,
                "y":82,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            /* 37 */{
                "x":0,
                "y":-82,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 38 */{
                "x":-557.5,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 39 */{
                "x":-557.5,
                "y":240,
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            /* 40 */{
                "x":-557.5,
                "y":-240,
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            /* 41 */{
                "x":-557.5,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 42 */{
                "x":557.5,
                "y":-240,
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            /* 43 */{
                "x":557.5,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 44 */{
                "x":557.5,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            /* 45 */{
                "x":557.5,
                "y":240,
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            /* 46 */{
                "x":0,
                "y":82,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 47 */{
                "x":-550,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 48 */{
                "x":-550,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 49 */{
                "x":550,
                "y":-80,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 50 */{
                "x":550,
                "y":80,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 51 */{
                "x":-548,
                "y":160,
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "color":"a3acc2"
            },
            /* 52 */{
                "x":-548,
                "y":-160,
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "color":"a3acc2"
            },
            /* 53 */{
                "x":548,
                "y":160,
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "color":"a3acc2"
            },
            /* 54 */{
                "x":548,
                "y":-160,
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "color":"a3acc2"
            },
            /* 55 */{
                "x":480,
                "y":-2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 56 */{
                "x":480,
                "y":2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 57 */{
                "x":480,
                "y":-2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 58 */{
                "x":480,
                "y":2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 59 */{
                "x":-480,
                "y":-2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 60 */{
                "x":-480,
                "y":2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 61 */{
                "x":-480,
                "y":-2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 62 */{
                "x":-480,
                "y":2,
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            /* 63 */{
                "x":16.883911680000004,
                "y":57.57619188060358,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"f5b602"
            },
            /* 64 */{
                "x":-31.012224000000018,
                "y":-7.9626350757750455,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"f5b602"
            },
            /* 65 */{
                "x":25.046845440000006,
                "y":51.05906944000002,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 66 */{
                "x":38.372712960000015,
                "y":36.814668800000014,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 67 */{
                "x":5.006300279396434,
                "y":25.924456840603572,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 68 */{
                "x":-19.84929024000001,
                "y":30.93075712000001,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 69 */{
                "x":-16.698957038792873,
                "y":-39.86956282030179,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 70 */{
                "x":-19.270973499698226,
                "y":-13.368160981508916,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 71 */{
                "x":5.572016460905348,
                "y":-13.722349662112483,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 72 */{
                "x":-9.860082304526747,
                "y":-63.299039780521255,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 73 */{
                "x":-7.288065843621398,
                "y":-52.153635116598075,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 74 */{
                "x":-7.288065843621398,
                "y":-42.72290809327846,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 75 */{
                "x":-16.718792866941012,
                "y":-46.98902606310015,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 76 */{
                "x":2.9999999999999982,
                "y":-30.720164609053494,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 77 */{
                "x":9.858710562414263,
                "y":0.14403292181069993,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 78 */{
                "x":25.29080932784636,
                "y":-3.2853223593964334,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 79 */{
                "x":16.71742112482853,
                "y":-34.149519890260635,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 80 */{
                "x":-3.0013717421124824,
                "y":3.5733882030178314,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 81 */{
                "x":35.57887517146776,
                "y":-5.857338820301783,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 82 */{
                "x":33.00685871056241,
                "y":6.1454046639231805,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 83 */{
                "x":11.573388203017831,
                "y":12.146776406035666,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 84 */{
                "x":19.289437585733882,
                "y":-52.153635116598075,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 85 */{
                "x":23.576131687242796,
                "y":-64.15637860082305,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 86 */{
                "x":7.286694101508916,
                "y":-72.72976680384087,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 87 */{
                "x":12.860082304526747,
                "y":-86.5912208504801,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 88 */{
                "x":14.574759945130314,
                "y":-101.16598079561042,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            }
        ],
        "segments":[
            {
                "v0":6,
                "v1":7,
                "color":"DB7F89",
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":7,
                "v1":8,
                "color":"DB7F89",
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":8,
                "v1":9,
                "color":"DB7F89",
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":10,
                "v1":11,
                "color":"7FA8DB",
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":11,
                "v1":12,
                "color":"7FA8DB",
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":12,
                "v1":13,
                "color":"7FA8DB",
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":2,
                "v1":3,
                "vis":false,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":3,
                "v1":4,
                "curve":180,
                "color":"a3acc2",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "blueKO"
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":4,
                "v1":3,
                "curve":180,
                "color":"a3acc2",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO"
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":4,
                "v1":5,
                "vis":false,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":14,
                "v1":15,
                "color":"a3acc2",
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":16,
                "v1":17,
                "color":"a3acc2",
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":18,
                "v1":19,
                "color":"a3acc2",
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":20,
                "v1":21,
                "color":"a3acc2",
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":22,
                "v1":23,
                "color":"a3acc2",
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":24,
                "v1":25,
                "color":"F8F8F8",
                "bCoef":0,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":26,
                "v1":27,
                "color":"a3acc2",
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":28,
                "v1":29,
                "color":"a3acc2",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":30,
                "v1":31,
                "color":"a3acc2",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":38,
                "v1":39,
                "vis":false,
                "color":"F8F8F8",
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":40,
                "v1":41,
                "vis":false,
                "color":"F8F8F8",
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":42,
                "v1":43,
                "vis":false,
                "color":"F8F8F8",
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":44,
                "v1":45,
                "vis":false,
                "color":"F8F8F8",
                "bCoef":2,
                "cMask":[
                    "ball"
                ]
            },
            {
                "v0":47,
                "v1":48,
                "color":"F8F8F8",
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            {
                "v0":49,
                "v1":50,
                "color":"F8F8F8",
                "bCoef":0.1,
                "cMask":[
                    
                ]
            },
            {
                "v0":52,
                "v1":51,
                "curve":180,
                "color":"a3acc2",
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":53,
                "v1":54,
                "curve":180,
                "color":"a3acc2",
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":56,
                "v1":55,
                "curve":180,
                "color":"686763",
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":57,
                "v1":58,
                "curve":180,
                "color":"686763",
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":60,
                "v1":59,
                "curve":180,
                "color":"686763",
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":61,
                "v1":62,
                "curve":180,
                "color":"686763",
                "bCoef":0.1,
                "cMask":[
                    
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":63,
                "v1":64,
                "curve":191.60416397318934,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":65,
                "v1":66,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":65,
                "v1":67,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":67,
                "v1":68,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":68,
                "v1":69,
                "curve":8.408996688972096,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":70,
                "v1":71,
                "curve":-47.13144030282425,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":69,
                "v1":72,
                "curve":190,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":72,
                "v1":69,
                "curve":190,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":72,
                "v1":73,
                "curve":190,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":73,
                "v1":72,
                "curve":162.05474677020808,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":74,
                "v1":75,
                "curve":40,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":76,
                "v1":77,
                "curve":40,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":78,
                "v1":79,
                "curve":40,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":76,
                "v1":79,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":77,
                "v1":78,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":80,
                "v1":81,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":81,
                "v1":82,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":82,
                "v1":83,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":80,
                "v1":83,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":84,
                "v1":85,
                "curve":-102.68038349182054,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":86,
                "v1":4,
                "curve":103.72033743034781,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":87,
                "v1":88,
                "curve":40,
                "color":"f5b602",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            }
        ],
        "planes":[
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-240,
                "cMask":[
                    "ball"
                ]
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-240,
                "cMask":[
                    "ball"
                ]
            },
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-270,
                "bCoef":0.1
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-270,
                "bCoef":0.1
            },
            {
                "normal":[
                    1,
                    0
                ],
                "dist":-642,
                "bCoef":0.1
            },
            {
                "normal":[
                    -1,
                    0
                ],
                "dist":-644,
                "bCoef":0.1
            },
            {
                "normal":[
                    1,
                    0
                ],
                "dist":-642,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "normal":[
                    -1,
                    0
                ],
                "dist":-643,
                "bCoef":0.1,
                "cMask":[
                    "ball"
                ]
            }
        ],
        "goals":[
            {
                "p0":[
                    -556.3,
                    -80
                ],
                "p1":[
                    -556.3,
                    80
                ],
                "team":"red"
            },
            {
                "p0":[
                    556.3,
                    80
                ],
                "p1":[
                    556.3,
                    -80
                ],
                "team":"blue"
            }
        ],
        "discs":[
            {
                "radius":5,
                "invMass":0,
                "pos":[
                    -550,
                    80
                ],
                "color":"E4E4E5"
            },
            {
                "radius":5,
                "invMass":0,
                "pos":[
                    -550,
                    -80
                ],
                "color":"E4E4E5"
            },
            {
                "radius":5,
                "invMass":0,
                "pos":[
                    550,
                    80
                ],
                "color":"E4E4E5"
            },
            {
                "radius":5,
                "invMass":0,
                "pos":[
                    550,
                    -80
                ],
                "color":"E4E4E5"
            }
        ],
        "playerPhysics":{
            "bCoef":0,
            "acceleration":0.11,
            "kickingAcceleration":0.083,
            "kickStrength":4.2
        },
        "ballPhysics":{
            "radius":5.8,
            "bCoef":0.412,
            "invMass":1.5,
            "color":"FFF26D"
        },
        "spawnDistance":350,
        "traits":{
            
        },
        "joints":[
            
        ],
        "redSpawnPoints":[
            
        ],
        "blueSpawnPoints":[
            
        ],
        "canBeStored":false
    }
    `
}

