import { stadiumInfo } from "./stadiumInfo";

export const stadium: stadiumInfo = {
    name: "4v4",
    minPlayers: 7,
    maxPlayers: 8,
    stadiumText: `
    {
        "name":"SINDICATO FOUR",
        "width":780,
        "height":350,
        "spawnDistance":350,
        "bg":{
            "type":"",
            "color":"2a3a40",
            "width":0,
            "height":0
        },
        "vertexes":[
            /* 0 */{
                "x":-700,
                "y":320,
                "trait":"ballArea",
                "bias":-15,
                "color":"a3acc2"
            },
            /* 1 */{
                "x":-700,
                "y":80,
                "trait":"ballArea",
                "bias":-15,
                "color":"a3acc2"
            },
            /* 2 */{
                "x":-700,
                "y":-80,
                "trait":"ballArea",
                "bias":-15,
                "color":"a3acc2"
            },
            /* 3 */{
                "x":-700,
                "y":-320,
                "trait":"ballArea",
                "bias":-15,
                "color":"a3acc2"
            },
            /* 4 */{
                "x":700,
                "y":320,
                "trait":"ballArea",
                "bias":15,
                "color":"a3acc2"
            },
            /* 5 */{
                "x":700,
                "y":80,
                "trait":"ballArea",
                "bias":15,
                "color":"a3acc2"
            },
            /* 6 */{
                "x":700,
                "y":-80,
                "trait":"ballArea",
                "bias":15,
                "color":"a3acc2"
            },
            /* 7 */{
                "x":700,
                "y":-320,
                "trait":"ballArea",
                "bias":15,
                "color":"a3acc2"
            },
            /* 8 */{
                "x":0,
                "y":320,
                "trait":"kickOffBarrier",
                "color":"a3acc2"
            },
            /* 9 */{
                "x":0,
                "y":80,
                "trait":"kickOffBarrier",
                "color":"a3acc2"
            },
            /* 10 */{
                "x":0,
                "y":-80,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"kickOffBarrier",
                "color":"a3acc2"
            },
            /* 11 */{
                "x":0,
                "y":-320,
                "trait":"kickOffBarrier",
                "color":"a3acc2"
            },
            /* 12 */{
                "x":-700,
                "y":-80,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 13 */{
                "x":-730,
                "y":-60,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 14 */{
                "x":-730,
                "y":60,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 15 */{
                "x":-700,
                "y":80,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 16 */{
                "x":700,
                "y":-80,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 17 */{
                "x":730,
                "y":-60,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 18 */{
                "x":730,
                "y":60,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 19 */{
                "x":700,
                "y":80,
                "trait":"goalNet",
                "color":"002033"
            },
            /* 20 */{
                "x":700,
                "y":-320,
                "trait":"line",
                "bias":15,
                "color":"a3acc2"
            },
            /* 21 */{
                "x":-700,
                "y":-320,
                "trait":"line",
                "bias":15,
                "color":"a3acc2"
            },
            /* 22 */{
                "x":700,
                "y":320,
                "trait":"line",
                "bias":-15,
                "color":"a3acc2"
            },
            /* 23 */{
                "x":-700,
                "y":320,
                "trait":"line",
                "bias":-15,
                "color":"a3acc2"
            },
            /* 24 */{
                "x":-700,
                "y":-80,
                "trait":"line",
                "color":"00290B"
            },
            /* 25 */{
                "x":-700,
                "y":80,
                "trait":"line",
                "color":"00290B"
            },
            /* 26 */{
                "x":700,
                "y":-80,
                "trait":"line",
                "color":"00290B"
            },
            /* 27 */{
                "x":700,
                "y":80,
                "trait":"line",
                "color":"00290B"
            },
            /* 28 */{
                "x":0,
                "y":320,
                "trait":"kickOffBarrier"
            },
            /* 29 */{
                "x":0,
                "y":350,
                "trait":"kickOffBarrier"
            },
            /* 30 */{
                "x":0,
                "y":-320,
                "trait":"kickOffBarrier"
            },
            /* 31 */{
                "x":0,
                "y":-350,
                "trait":"kickOffBarrier"
            },
            /* 32 */{
                "x":-700,
                "y":275,
                "trait":"line"
            },
            /* 33 */{
                "x":700,
                "y":275,
                "trait":"line"
            },
            /* 34 */{
                "x":700,
                "y":-275,
                "trait":"line"
            },
            /* 35 */{
                "x":-690,
                "y":-320,
                "trait":"line",
                "color":"007D11"
            },
            /* 36 */{
                "x":-700,
                "y":-310,
                "trait":"line",
                "color":"007D11"
            },
            /* 37 */{
                "x":-700,
                "y":310,
                "trait":"line",
                "color":"007D11"
            },
            /* 38 */{
                "x":-690,
                "y":320,
                "trait":"line",
                "color":"007D11"
            },
            /* 39 */{
                "x":700,
                "y":310,
                "trait":"line",
                "color":"007D11"
            },
            /* 40 */{
                "x":690,
                "y":320,
                "trait":"line",
                "color":"007D11"
            },
            /* 41 */{
                "x":690,
                "y":-320,
                "trait":"line",
                "color":"007D11"
            },
            /* 42 */{
                "x":700,
                "y":-310,
                "trait":"line",
                "color":"007D11"
            },
            /* 43 */{
                "x":-700,
                "y":-80,
                "trait":"ballArea"
            },
            /* 44 */{
                "x":-700,
                "y":-320,
                "trait":"ballArea"
            },
            /* 45 */{
                "x":-700,
                "y":320,
                "trait":"ballArea"
            },
            /* 46 */{
                "x":-700,
                "y":80,
                "trait":"ballArea"
            },
            /* 47 */{
                "x":700,
                "y":320,
                "trait":"ballArea"
            },
            /* 48 */{
                "x":700,
                "y":80,
                "trait":"ballArea"
            },
            /* 49 */{
                "x":700,
                "y":-80,
                "trait":"ballArea"
            },
            /* 50 */{
                "x":700,
                "y":-320,
                "trait":"ballArea"
            },
            /* 51 */{
                "x":-450,
                "y":-321.59374237060547,
                "bCoef":-0.5,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "color":"a3a3a3"
            },
            /* 52 */{
                "x":-450,
                "y":319.40625762939453,
                "bCoef":-0.5,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "color":"a3a3a3"
            },
            /* 53 */{
                "x":450,
                "y":-321.59374237060547,
                "bCoef":-0.5,
                "cMask":[
                    "ball"
                ],
                "trait":"goalNet",
                "color":"a3a3a3"
            },
            /* 54 */{
                "x":450,
                "y":319.40625762939453,
                "bCoef":-0.5,
                "cMask":[
                    "ball"
                ],
                "trait":"goalNet",
                "color":"a3a3a3"
            },
            /* 55 */{
                "x":-400,
                "y":-319,
                "trait":"line",
                "curve":0,
                "color":"a3acc2"
            },
            /* 56 */{
                "x":-400,
                "y":318,
                "trait":"line",
                "curve":0,
                "color":"a3acc2"
            },
            /* 57 */{
                "x":400,
                "y":-319,
                "trait":"line",
                "curve":0,
                "color":"a3acc2"
            },
            /* 58 */{
                "x":400,
                "y":318,
                "trait":"line",
                "curve":0,
                "color":"a3acc2"
            },
            /* 59 */{
                "x":-700,
                "y":-130,
                "trait":"line",
                "curve":0,
                "color":"a3acc2"
            },
            /* 60 */{
                "x":-595,
                "y":-130,
                "trait":"line",
                "curve":50,
                "color":"a3acc2"
            },
            /* 61 */{
                "x":700,
                "y":-130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 62 */{
                "x":595,
                "y":-130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 63 */{
                "x":-700,
                "y":130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 64 */{
                "x":-595,
                "y":130,
                "trait":"line",
                "curve":0,
                "color":"a3acc2"
            },
            /* 65 */{
                "x":700,
                "y":130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 66 */{
                "x":595,
                "y":130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 67 */{
                "x":-399,
                "y":-136,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 68 */{
                "x":-402,
                "y":130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 69 */{
                "x":399,
                "y":-136,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 70 */{
                "x":402,
                "y":130,
                "trait":"line",
                "color":"a3acc2"
            },
            /* 71 */{
                "x":21.6,
                "y":54.00000000000002,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 72 */{
                "x":-32.40000000000001,
                "y":-4.319999999999996,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 73 */{
                "x":30.240000000000006,
                "y":45.360000000000014,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 74 */{
                "x":44.28000000000001,
                "y":30.240000000000006,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 75 */{
                "x":11.88,
                "y":22.680000000000007,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 76 */{
                "x":-15.120000000000005,
                "y":29.160000000000007,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 77 */{
                "x":-20.520000000000003,
                "y":-36.720000000000006,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 78 */{
                "x":-19.440000000000005,
                "y":-4.32,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 79 */{
                "x":7.5600000000000005,
                "y":-10.800000000000002,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 80 */{
                "x":-16.200000000000003,
                "y":-64.80000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 81 */{
                "x":-10.800000000000002,
                "y":-42.12000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 82 */{
                "x":-22.680000000000007,
                "y":-47.52000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 83 */{
                "x":-8.640000000000002,
                "y":-60.48000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 84 */{
                "x":-15.120000000000003,
                "y":-51.84000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 85 */{
                "x":5.400000000000001,
                "y":-34.56000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 86 */{
                "x":12.960000000000003,
                "y":5.400000000000002,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 87 */{
                "x":30.240000000000002,
                "y":0,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 88 */{
                "x":21.600000000000005,
                "y":-37.80000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 89 */{
                "x":1.0800000000000003,
                "y":6.480000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 90 */{
                "x":42.12000000000001,
                "y":-2.1600000000000006,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 91 */{
                "x":37.800000000000004,
                "y":6.480000000000002,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 92 */{
                "x":9.719999999999999,
                "y":14.040000000000004,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 93 */{
                "x":23.760000000000005,
                "y":-69.12000000000002,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 94 */{
                "x":19.440000000000005,
                "y":-54.000000000000014,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 95 */{
                "x":-8.400000000000002,
                "y":-94.64000000000001,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 96 */{
                "x":9.720000000000002,
                "y":-117.72000000000003,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            /* 97 */{
                "x":11.880000000000003,
                "y":-99.36000000000003,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            }
        ],
        "segments":[
            {
                "v0":43,
                "v1":44,
                "trait":"ballArea"
            },
            {
                "v0":45,
                "v1":46,
                "trait":"ballArea"
            },
            {
                "v0":47,
                "v1":48,
                "trait":"ballArea"
            },
            {
                "v0":49,
                "v1":50,
                "trait":"ballArea"
            },
            {
                "v0":0,
                "v1":1,
                "vis":true,
                "color":"a3acc2",
                "trait":"ballArea",
                "bias":-15
            },
            {
                "v0":2,
                "v1":3,
                "vis":true,
                "color":"a3acc2",
                "trait":"ballArea",
                "bias":-15
            },
            {
                "v0":4,
                "v1":5,
                "vis":true,
                "color":"a3acc2",
                "trait":"ballArea",
                "bias":15
            },
            {
                "v0":6,
                "v1":7,
                "vis":true,
                "color":"a3acc2",
                "trait":"ballArea",
                "bias":15
            },
            {
                "v0":16,
                "v1":17,
                "curve":90,
                "color":"002033",
                "trait":"goalNet"
            },
            {
                "v0":18,
                "v1":19,
                "curve":90,
                "color":"002033",
                "trait":"goalNet"
            },
            {
                "v0":12,
                "v1":13,
                "curve":-90,
                "color":"002033",
                "trait":"goalNet"
            },
            {
                "v0":14,
                "v1":15,
                "curve":-90,
                "color":"002033",
                "trait":"goalNet"
            },
            {
                "v0":13,
                "v1":14,
                "color":"002033",
                "trait":"goalNet"
            },
            {
                "v0":17,
                "v1":18,
                "color":"002033",
                "trait":"goalNet"
            },
            {
                "v0":9,
                "v1":10,
                "curve":180,
                "color":"a3acc2",
                "cGroup":[
                    "blueKO"
                ],
                "trait":"kickOffBarrier"
            },
            {
                "v0":9,
                "v1":10,
                "curve":-180,
                "color":"a3acc2",
                "cGroup":[
                    "redKO"
                ],
                "trait":"kickOffBarrier"
            },
            {
                "v0":28,
                "v1":29,
                "vis":false,
                "trait":"kickOffBarrier"
            },
            {
                "v0":30,
                "v1":31,
                "vis":false,
                "trait":"kickOffBarrier"
            },
            {
                "v0":8,
                "v1":9,
                "color":"a3acc2",
                "trait":"kickOffBarrier"
            },
            {
                "v0":10,
                "v1":11,
                "color":"a3acc2",
                "trait":"kickOffBarrier"
            },
            {
                "v0":35,
                "v1":36,
                "curve":90,
                "color":"007D11",
                "trait":"line"
            },
            {
                "v0":37,
                "v1":38,
                "curve":90,
                "color":"007D11",
                "trait":"line"
            },
            {
                "v0":39,
                "v1":40,
                "curve":-90,
                "color":"007D11",
                "trait":"line"
            },
            {
                "v0":41,
                "v1":42,
                "curve":-90,
                "color":"007D11",
                "trait":"line"
            },
            {
                "v0":20,
                "v1":21,
                "color":"a3acc2",
                "trait":"line",
                "bias":15
            },
            {
                "v0":22,
                "v1":23,
                "color":"a3acc2",
                "trait":"line",
                "bias":-15
            },
            {
                "v0":24,
                "v1":25,
                "color":"00290B",
                "trait":"line"
            },
            {
                "v0":26,
                "v1":27,
                "color":"00290B",
                "trait":"line"
            },
            {
                "v0":55,
                "v1":56,
                "curve":0,
                "color":"a3acc2",
                "trait":"line",
                "x":-400
            },
            {
                "v0":57,
                "v1":58,
                "curve":0,
                "color":"a3acc2",
                "trait":"line",
                "x":400
            },
            {
                "v0":59,
                "v1":60,
                "curve":0,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":61,
                "v1":62,
                "curve":0,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":63,
                "v1":64,
                "curve":0,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":65,
                "v1":66,
                "curve":0,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":60,
                "v1":64,
                "curve":0,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":62,
                "v1":66,
                "curve":0,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":67,
                "v1":68,
                "curve":140,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":69,
                "v1":70,
                "curve":-140,
                "color":"a3acc2",
                "trait":"line"
            },
            {
                "v0":71,
                "v1":72,
                "curve":180,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":73,
                "v1":74,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":73,
                "v1":75,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":75,
                "v1":76,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":76,
                "v1":77,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":78,
                "v1":79,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":77,
                "v1":80,
                "curve":190,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":80,
                "v1":77,
                "curve":172.93541083221805,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":81,
                "v1":82,
                "curve":90,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":83,
                "v1":84,
                "curve":190,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":84,
                "v1":83,
                "curve":190,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":85,
                "v1":86,
                "curve":30.922435480883802,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":87,
                "v1":88,
                "curve":56.144973871705886,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":85,
                "v1":88,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":86,
                "v1":87,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":89,
                "v1":90,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":90,
                "v1":91,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":91,
                "v1":92,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":89,
                "v1":92,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":93,
                "v1":94,
                "curve":40,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":10,
                "v1":95,
                "curve":40,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            },
            {
                "v0":96,
                "v1":97,
                "curve":40,
                "color":"f5b602",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "bias":2
            }
        ],
        "goals":[
            {
                "p0":[
                    -710,
                    -80
                ],
                "p1":[
                    -710,
                    80
                ],
                "team":"red"
            },
            {
                "p0":[
                    710,
                    80
                ],
                "p1":[
                    710,
                    -80
                ],
                "team":"blue"
            }
        ],
        "discs":[
            {
                "radius":5.9,
                "pos":[
                    -700,
                    80
                ],
                "color":"000203",
                "trait":"goalPost"
            },
            {
                "radius":5.9,
                "pos":[
                    -700,
                    -80
                ],
                "color":"000203",
                "trait":"goalPost"
            },
            {
                "radius":5.9,
                "pos":[
                    700,
                    80
                ],
                "color":"000203",
                "trait":"goalPost"
            },
            {
                "radius":5.9,
                "pos":[
                    700,
                    -80
                ],
                "color":"000203",
                "trait":"goalPost"
            }
        ],
        "planes":[
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-320,
                "trait":"ballArea"
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-320,
                "trait":"ballArea"
            },
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-350,
                "bCoef":0
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-350,
                "bCoef":0
            },
            {
                "normal":[
                    1,
                    0
                ],
                "dist":-780,
                "bCoef":0
            },
            {
                "normal":[
                    -1,
                    0
                ],
                "dist":-780,
                "bCoef":0
            }
        ],
        "traits":{
            "line":{
                "cMask":[
                    ""
                ],
                "color":"FFFFFF"
            },
            "ballArea":{
                "vis":false,
                "bCoef":1,
                "cMask":[
                    "ball"
                ]
            },
            "goalPost":{
                "radius":8,
                "invMass":0,
                "color":"E50808"
            },
            "goalNet":{
                "bCoef":-0.5,
                "cMask":[
                    "ball"
                ]
            },
            "kickOffBarrier":{
                "bCoef":0.1,
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "cMask":[
                    "red",
                    "blue"
                ],
                "color":"FFFFFF"
            }
        },
        "playerPhysics":{
            "bCoef":0.01,
            "kickStrength":4.545,
            "kickingAcceleration":0.09,
            "acceleration":0.113
        },
        "ballPhysics":{
            "radius":5.9,
            "bCoef":0.42,
            "color":"820400",
            "invMass":1.5,
            "damping":0.99
        },
        "joints":[
            
        ],
        "redSpawnPoints":[
            
        ],
        "blueSpawnPoints":[
            
        ],
        "canBeStored":false
    }
    `
};