import { stadiumInfo } from "./stadiumInfo";

export const stadium: stadiumInfo = {
    name: "6v6",
    minPlayers: 9,
    maxPlayers: 12,
    stadiumText: `
    {
        "name":"SINDICATO SIX",
        "width":1025,
        "height":490,
        "spawnDistance":450,
        "bg":{
            "color":"2a3a40"
        },
        "vertexes":[
            {
                "x":-950,
                "y":460,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":-950,
                "y":95,
                "bCoef":1.15,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "color":"ff0000"
            },
            {
                "x":-950,
                "y":-95,
                "bCoef":1.15,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "color":"ff0000"
            },
            {
                "x":-950,
                "y":-460,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":950,
                "y":456,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":950,
                "y":95,
                "bCoef":1.15,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "color":"0000ff"
            },
            {
                "x":950,
                "y":-95,
                "bCoef":1.15,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "color":"0000ff"
            },
            {
                "x":950,
                "y":-456,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":0,
                "y":495,
                "trait":"kickOffBarrier"
            },
            {
                "x":0,
                "y":130,
                "trait":"kickOffBarrier"
            },
            {
                "x":0,
                "y":-130,
                "trait":"line"
            },
            {
                "x":0,
                "y":-495,
                "trait":"kickOffBarrier"
            },
            {
                "x":-1000,
                "y":-95,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "curve":0
            },
            {
                "x":1000,
                "y":-95,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "curve":0
            },
            {
                "x":-1000,
                "y":95,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "curve":0
            },
            {
                "x":1000,
                "y":95,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "curve":0
            },
            {
                "x":951,
                "y":460,
                "bCoef":1,
                "trait":"ballArea"
            },
            {
                "x":951,
                "y":-460,
                "bCoef":1,
                "trait":"ballArea"
            },
            {
                "x":0,
                "y":130,
                "trait":"kickOffBarrier"
            },
            {
                "x":0,
                "y":-130,
                "trait":"kickOffBarrier"
            },
            {
                "x":956.75,
                "y":-101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":956.75,
                "y":-460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":-956.75,
                "y":-101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":-956.75,
                "y":-460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":-956.75,
                "y":101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":-956.75,
                "y":460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":956.75,
                "y":101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":956.75,
                "y":460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":640,
                "y":100,
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line",
                "curve":-90
            },
            {
                "x":850,
                "y":330,
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line",
                "curve":-90
            },
            {
                "x":640,
                "y":-100,
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line",
                "curve":90
            },
            {
                "x":-450,
                "y":460,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":950,
                "y":200,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":950,
                "y":-200,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":-450,
                "y":-460,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":450,
                "y":460,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":450,
                "y":-460,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":-950,
                "y":-200,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":-950,
                "y":200,
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "x":-950,
                "y":435,
                "bCoef":0.1,
                "trait":"line",
                "curve":-90
            },
            {
                "x":-925,
                "y":460,
                "bCoef":0.1,
                "trait":"line",
                "curve":-90
            },
            {
                "x":-950,
                "y":-435,
                "bCoef":0.1,
                "trait":"line",
                "curve":90
            },
            {
                "x":-925,
                "y":-460,
                "bCoef":0.1,
                "trait":"line",
                "curve":90
            },
            {
                "x":950,
                "y":-435,
                "bCoef":0.1,
                "trait":"line",
                "curve":-90
            },
            {
                "x":925,
                "y":-460,
                "bCoef":0.1,
                "trait":"line",
                "curve":-90
            },
            {
                "x":950,
                "y":435,
                "bCoef":0.1,
                "trait":"line",
                "curve":90
            },
            {
                "x":925,
                "y":460,
                "bCoef":0.1,
                "trait":"line",
                "curve":90
            },
            {
                "x":850,
                "y":-330,
                "bCoef":0,
                "trait":"line",
                "curve":90
            },
            {
                "x":-640,
                "y":100,
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line",
                "curve":90
            },
            {
                "x":-850,
                "y":330,
                "bCoef":0,
                "trait":"line",
                "curve":90
            },
            {
                "x":-640,
                "y":-100,
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line",
                "curve":-90
            },
            {
                "x":-850,
                "y":-330,
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line",
                "curve":-90
            },
            {
                "x":-950,
                "y":330,
                "bCoef":0,
                "trait":"line"
            },
            {
                "x":-950,
                "y":-330,
                "bCoef":0,
                "trait":"line"
            },
            {
                "x":950,
                "y":330,
                "bCoef":0,
                "trait":"line"
            },
            {
                "x":950,
                "y":-330,
                "bCoef":0,
                "trait":"line"
            },
            {
                "x":-640,
                "y":-4.7,
                "bCoef":0.1,
                "trait":"line",
                "curve":180
            },
            {
                "x":-640,
                "y":4.7,
                "bCoef":0.1,
                "trait":"line",
                "curve":180
            },
            {
                "x":640,
                "y":-4.7,
                "bCoef":0.1,
                "trait":"line",
                "curve":180
            },
            {
                "x":640,
                "y":4.7,
                "bCoef":0.1,
                "trait":"line",
                "curve":180
            },
            {
                "x":950,
                "y":-30,
                "bCoef":0.1,
                "trait":"line",
                "color":"0000b0"
            },
            {
                "x":950,
                "y":30,
                "bCoef":0.1,
                "trait":"line",
                "color":"0000b0"
            },
            {
                "x":-950,
                "y":-30,
                "cMask":[
                    "wall"
                ],
                "color":"b00000"
            },
            {
                "x":-950,
                "y":30,
                "cMask":[
                    "wall"
                ],
                "color":"b00000"
            },
            {
                "x":-1006.5,
                "y":101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "x":-1006.5,
                "y":-101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "x":1006.5,
                "y":-101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "x":1006.5,
                "y":101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ]
            },
            {
                "x":0,
                "y":-460,
                "cMask":[
                    "wall"
                ],
                "vis":true,
                "color":"ffffff"
            },
            {
                "x":0,
                "y":-130,
                "cMask":[
                    "wall"
                ],
                "vis":true,
                "color":"ffffff"
            },
            {
                "x":0,
                "y":460,
                "cMask":[
                    "wall"
                ],
                "vis":true,
                "color":"ffffff"
            },
            {
                "x":0,
                "y":130,
                "cMask":[
                    "wall"
                ],
                "vis":true,
                "color":"ffffff"
            },
            {
                "x":-957.25,
                "y":101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":-957.25,
                "y":460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":957.25,
                "y":101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":957.25,
                "y":460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":957.25,
                "y":-101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":957.25,
                "y":-460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":-957.25,
                "y":-101.5,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"line",
                "curve":0
            },
            {
                "x":-957.25,
                "y":-460,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0
            },
            {
                "x":54.74834938021254,
                "y":87.27887792101639,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-49.98298545680249,
                "y":-20.628576039175655,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":58.74358583549255,
                "y":75.4140628969161,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":77.00172737895645,
                "y":58.74358583549255,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":20.63963826652441,
                "y":32.54712188182695,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-30.16562515876644,
                "y":41.279276533048815,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-31.753289640806777,
                "y":-65.0942437636539,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-29.87945739978661,
                "y":-19.937960676726103,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":14.289368490575637,
                "y":-24.764460702128737,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-29.371792917746276,
                "y":-114.31184270690441,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-13.495148097342883,
                "y":-107.96118477874306,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-18.2581415434639,
                "y":-92.87837219935984,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-10.319819133262204,
                "y":-73.0325661738556,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":-35.72245084590763,
                "y":-79.38322410201695,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":9.018710562414274,
                "y":-51.61733882030179,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":17.658710562414274,
                "y":-5.177338820301784,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":43.57871056241428,
                "y":-11.657338820301785,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":26.298710562414275,
                "y":-54.85733882030179,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":1.2360493827160586,
                "y":-1.2693552812071338,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":61.11467764060358,
                "y":-17.057338820301787,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":55.72702331961591,
                "y":-3.4293552812071324,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":15.432098765432107,
                "y":7.71604938271605,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "color":"0080ff"
            },
            {
                "x":22.000000000000004,
                "y":-116.4814814814815,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":75
            },
            {
                "x":24.777777777777782,
                "y":-145.18518518518522,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":75
            },
            {
                "x":-3.148148148148149,
                "y":-139.5925925925926,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":90
            },
            {
                "x":-13.333333333333334,
                "y":-161.81481481481484,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":90
            },
            {
                "x":16.740740740740748,
                "y":-76.14814814814815,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":-50
            },
            {
                "x":11.185185185185189,
                "y":-93.74074074074075,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":-50
            }
        ],
        "segments":[
            {
                "v0":0,
                "v1":1,
                "curve":0,
                "trait":"ballArea"
            },
            {
                "v0":2,
                "v1":3,
                "trait":"ballArea"
            },
            {
                "v0":4,
                "v1":5,
                "trait":"ballArea",
                "x":951
            },
            {
                "v0":6,
                "v1":7,
                "trait":"ballArea",
                "x":951
            },
            {
                "v0":8,
                "v1":9,
                "trait":"kickOffBarrier",
                "x":0
            },
            {
                "v0":9,
                "v1":10,
                "curve":180,
                "cGroup":[
                    "blueKO"
                ],
                "trait":"kickOffBarrier"
            },
            {
                "v0":9,
                "v1":10,
                "curve":-180,
                "cGroup":[
                    "redKO"
                ],
                "trait":"kickOffBarrier"
            },
            {
                "v0":10,
                "v1":11,
                "trait":"kickOffBarrier",
                "x":0
            },
            {
                "v0":2,
                "v1":12,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "y":-95
            },
            {
                "v0":6,
                "v1":13,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "y":-95
            },
            {
                "v0":1,
                "v1":14,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "y":95
            },
            {
                "v0":5,
                "v1":15,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "y":95
            },
            {
                "v0":12,
                "v1":14,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "x":-1000
            },
            {
                "v0":13,
                "v1":15,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalNet",
                "x":1000
            },
            {
                "v0":1,
                "v1":0,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-950
            },
            {
                "v0":5,
                "v1":4,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":950
            },
            {
                "v0":2,
                "v1":3,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-950
            },
            {
                "v0":6,
                "v1":7,
                "curve":0,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":950
            },
            {
                "v0":0,
                "v1":16,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":1,
                "trait":"ballArea",
                "y":460
            },
            {
                "v0":3,
                "v1":17,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":1,
                "trait":"ballArea",
                "y":-460
            },
            {
                "v0":10,
                "v1":9,
                "curve":-180,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0,
                "trait":"line"
            },
            {
                "v0":19,
                "v1":18,
                "curve":180,
                "vis":true,
                "color":"FFFFFF",
                "bCoef":0,
                "trait":"line"
            },
            {
                "v0":2,
                "v1":1,
                "curve":0,
                "vis":true,
                "color":"ff0000",
                "bCoef":0,
                "trait":"line",
                "x":-950
            },
            {
                "v0":6,
                "v1":5,
                "curve":0,
                "vis":true,
                "color":"0000ff",
                "bCoef":0,
                "trait":"line"
            },
            {
                "v0":20,
                "v1":21,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":956.75
            },
            {
                "v0":22,
                "v1":23,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-956.75
            },
            {
                "v0":24,
                "v1":25,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-956.75
            },
            {
                "v0":26,
                "v1":27,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":956.75
            },
            {
                "v0":28,
                "v1":29,
                "curve":-90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line"
            },
            {
                "v0":40,
                "v1":39,
                "curve":-90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "v0":42,
                "v1":41,
                "curve":90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "v0":44,
                "v1":43,
                "curve":-90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "v0":46,
                "v1":45,
                "curve":90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "v0":30,
                "v1":47,
                "curve":90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line"
            },
            {
                "v0":48,
                "v1":49,
                "curve":90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line"
            },
            {
                "v0":50,
                "v1":51,
                "curve":-90,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "cMask":[
                    ""
                ],
                "trait":"line"
            },
            {
                "v0":49,
                "v1":52,
                "curve":0,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line",
                "y":330
            },
            {
                "v0":51,
                "v1":53,
                "curve":0,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line",
                "y":-330
            },
            {
                "v0":48,
                "v1":50,
                "curve":0,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line",
                "x":-640
            },
            {
                "v0":29,
                "v1":54,
                "curve":0,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line",
                "y":330
            },
            {
                "v0":47,
                "v1":55,
                "curve":0,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line",
                "y":-330
            },
            {
                "v0":28,
                "v1":30,
                "curve":0,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0,
                "trait":"line",
                "x":640
            },
            {
                "v0":56,
                "v1":57,
                "curve":120,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":-640
            },
            {
                "v0":57,
                "v1":56,
                "curve":180,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":-640
            },
            {
                "v0":56,
                "v1":57,
                "curve":180,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":-640
            },
            {
                "v0":57,
                "v1":56,
                "curve":120,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":-640
            },
            {
                "v0":58,
                "v1":59,
                "curve":120,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":640
            },
            {
                "v0":59,
                "v1":58,
                "curve":180,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":640
            },
            {
                "v0":58,
                "v1":59,
                "curve":180,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":640
            },
            {
                "v0":59,
                "v1":58,
                "curve":120,
                "vis":true,
                "color":"F8F8F8",
                "bCoef":0.1,
                "trait":"line",
                "x":640
            },
            {
                "v0":60,
                "v1":61,
                "curve":0,
                "vis":true,
                "color":"0000b0",
                "bCoef":0.1,
                "trait":"line",
                "x":950
            },
            {
                "v0":62,
                "v1":63,
                "curve":0,
                "vis":true,
                "color":"b00000",
                "cMask":[
                    "wall"
                ],
                "x":-950
            },
            {
                "v0":24,
                "v1":64,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "y":101.5
            },
            {
                "v0":64,
                "v1":65,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "x":-1006.5
            },
            {
                "v0":65,
                "v1":22,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "y":-101.5
            },
            {
                "v0":20,
                "v1":66,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "y":-101.5
            },
            {
                "v0":66,
                "v1":67,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "x":1006.5
            },
            {
                "v0":67,
                "v1":26,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "y":101.5
            },
            {
                "v0":68,
                "v1":69,
                "vis":true,
                "color":"ffffff",
                "cMask":[
                    "wall"
                ],
                "x":0
            },
            {
                "v0":70,
                "v1":71,
                "vis":true,
                "color":"ffffff",
                "cMask":[
                    "wall"
                ],
                "x":0
            },
            {
                "v0":72,
                "v1":73,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-957.25
            },
            {
                "v0":74,
                "v1":75,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":957.25
            },
            {
                "v0":76,
                "v1":77,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":957.25
            },
            {
                "v0":78,
                "v1":79,
                "curve":0,
                "vis":false,
                "color":"FFFFFF",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-957.25
            },
            {
                "v0":80,
                "v1":81,
                "curve":188.84150569912845,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":82,
                "v1":83,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":82,
                "v1":84,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":84,
                "v1":85,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":85,
                "v1":86,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":87,
                "v1":88,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":86,
                "v1":89,
                "curve":188.84150569912845,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":89,
                "v1":86,
                "curve":188.84150569912845,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":90,
                "v1":91,
                "curve":190,
                "color":"FFFFFF",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":90,
                "v1":91,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":91,
                "v1":90,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":92,
                "v1":93,
                "curve":50,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":94,
                "v1":95,
                "curve":40,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":96,
                "v1":97,
                "curve":40,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":94,
                "v1":97,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":95,
                "v1":96,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":98,
                "v1":99,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":99,
                "v1":100,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":100,
                "v1":101,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":98,
                "v1":101,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":102,
                "v1":103,
                "curve":75,
                "color":"505050",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":104,
                "v1":105,
                "curve":90,
                "color":"505050",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":106,
                "v1":107,
                "curve":-50,
                "color":"505050",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            }
        ],
        "goals":[
            {
                "p0":[
                    -958.1,
                    -95
                ],
                "p1":[
                    -958.1,
                    95
                ],
                "team":"red"
            },
            {
                "p0":[
                    958.1,
                    95
                ],
                "p1":[
                    958.1,
                    -95
                ],
                "team":"blue"
            }
        ],
        "discs":[
            {
                "radius":5.4,
                "pos":[
                    -950,
                    95
                ],
                "color":"ff0000",
                "bCoef":0.55,
                "trait":"goalPost"
            },
            {
                "radius":5.4,
                "pos":[
                    -950,
                    -95
                ],
                "color":"ff0000",
                "bCoef":0.55,
                "trait":"goalPost"
            },
            {
                "radius":5.4,
                "pos":[
                    950,
                    95
                ],
                "color":"0000ff",
                "bCoef":0.55,
                "trait":"goalPost"
            },
            {
                "radius":5.4,
                "pos":[
                    950,
                    -95
                ],
                "color":"0000ff",
                "bCoef":0.55,
                "trait":"goalPost"
            },
            {
                "radius":3,
                "invMass":0,
                "pos":[
                    -950,
                    460
                ],
                "color":"FFCC00",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "radius":3,
                "invMass":0,
                "pos":[
                    -950,
                    -460
                ],
                "color":"FFCC00",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "radius":3,
                "invMass":0,
                "pos":[
                    950,
                    -460
                ],
                "color":"FFCC00",
                "bCoef":0.1,
                "trait":"line"
            },
            {
                "radius":3,
                "invMass":0,
                "pos":[
                    950,
                    460
                ],
                "color":"FFCC00",
                "bCoef":0.1,
                "trait":"line"
            }
        ],
        "planes":[
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-460,
                "trait":"ballArea",
                "_data":{
                    "extremes":{
                        "normal":[
                            0,
                            1
                        ],
                        "dist":-460,
                        "canvas_rect":[
                            -515.2564361454026,
                            -247.62323873007213,
                            515.2564361454026,
                            247.62323873007213
                        ],
                        "a":[
                            -515.2564361454026,
                            -460
                        ],
                        "b":[
                            515.2564361454026,
                            -460
                        ]
                    }
                }
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-460,
                "trait":"ballArea",
                "_data":{
                    "extremes":{
                        "normal":[
                            0,
                            -1
                        ],
                        "dist":-460,
                        "canvas_rect":[
                            -515.2564361454026,
                            -247.62323873007213,
                            515.2564361454026,
                            247.62323873007213
                        ],
                        "a":[
                            -515.2564361454026,
                            460
                        ],
                        "b":[
                            515.2564361454026,
                            460
                        ]
                    }
                }
            },
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-495,
                "bCoef":0.2,
                "cMask":[
                    "all"
                ],
                "_data":{
                    "extremes":{
                        "normal":[
                            0,
                            1
                        ],
                        "dist":-495,
                        "canvas_rect":[
                            -515.2564361454026,
                            -247.62323873007213,
                            515.2564361454026,
                            247.62323873007213
                        ],
                        "a":[
                            -515.2564361454026,
                            -495
                        ],
                        "b":[
                            515.2564361454026,
                            -495
                        ]
                    }
                }
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-495,
                "bCoef":0.2,
                "cMask":[
                    "all"
                ],
                "_data":{
                    "extremes":{
                        "normal":[
                            0,
                            -1
                        ],
                        "dist":-495,
                        "canvas_rect":[
                            -515.2564361454026,
                            -247.62323873007213,
                            515.2564361454026,
                            247.62323873007213
                        ],
                        "a":[
                            -515.2564361454026,
                            495
                        ],
                        "b":[
                            515.2564361454026,
                            495
                        ]
                    }
                }
            },
            {
                "normal":[
                    1,
                    0
                ],
                "dist":-1030,
                "bCoef":0.2,
                "cMask":[
                    "all"
                ],
                "_data":{
                    "extremes":{
                        "normal":[
                            1,
                            0
                        ],
                        "dist":-1030,
                        "canvas_rect":[
                            -515.2564361454026,
                            -247.62323873007213,
                            515.2564361454026,
                            247.62323873007213
                        ],
                        "a":[
                            -1030,
                            -247.62323873007213
                        ],
                        "b":[
                            -1030,
                            247.62323873007213
                        ]
                    }
                }
            },
            {
                "normal":[
                    -1,
                    0
                ],
                "dist":-1030,
                "bCoef":0.2,
                "cMask":[
                    "all"
                ],
                "_data":{
                    "extremes":{
                        "normal":[
                            -1,
                            0
                        ],
                        "dist":-1030,
                        "canvas_rect":[
                            -515.2564361454026,
                            -247.62323873007213,
                            515.2564361454026,
                            247.62323873007213
                        ],
                        "a":[
                            1030,
                            -247.62323873007213
                        ],
                        "b":[
                            1030,
                            247.62323873007213
                        ]
                    }
                }
            }
        ],
        "traits":{
            "ballArea":{
                "vis":false,
                "bCoef":1,
                "cMask":[
                    "ball"
                ]
            },
            "goalPost":{
                "radius":8,
                "invMass":0,
                "bCoef":1
            },
            "goalNet":{
                "vis":true,
                "bCoef":0.1,
                "cMask":[
                    "all"
                ]
            },
            "kickOffBarrier":{
                "vis":false,
                "bCoef":0.1,
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "cMask":[
                    "red",
                    "blue"
                ]
            },
            "line":{
                "vis":true,
                "bCoef":0,
                "cMask":[
                    ""
                ]
            },
            "arco":{
                "radius":2,
                "cMask":[
                    "n/d"
                ],
                "color":"cccccc"
            },
            "rusito":{
                "color":"444749"
            },
            "assad":{
                "color":"444749"
            }
        },
        "playerPhysics":{
            "bCoef":0.1,
            "acceleration":0.11,
            "kickingAcceleration":0.083,
            "kickStrength":4.9,
            "radius":15,
            "invMass":0.5,
            "damping":0.96,
            "cGroup":[
                "red",
                "blue"
            ],
            "gravity":[
                0,
                0
            ],
            "kickingDamping":0.96,
            "kickback":0
        },
        "ballPhysics":{
            "radius":6.25,
            "bCoef":0.35,
            "invMass":1.5,
            "color":"FFCC00",
            "cMask":[
                "all"
            ],
            "damping":0.99,
            "gravity":[
                0,
                0
            ],
            "cGroup":[
                "ball"
            ]
        },
        "canBeStored":false,
        "joints":[
            
        ],
        "redSpawnPoints":[
            
        ],
        "blueSpawnPoints":[
            
        ],
        "cameraWidth":0,
        "cameraHeight":0,
        "maxViewWidth":0,
        "cameraFollow":"ball",
        "kickOffReset":"partial"
    }
    `
};