import { stadiumInfo } from "./stadiumInfo";

export const stadium: stadiumInfo = {
    name: "7v7",
    minPlayers: 13,
    maxPlayers: 14,
    stadiumText: `
    {
        "name":"SINDICATO SEVEN",
        "canBeStored":false,
        "width":1265,
        "height":630,
        "bg":{
            "type":"",
            "color":"2a3a40",
            "width":0,
            "height":0
        },
        "vertexes":[
            {
                "x":0,
                "y":-631,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "x":0,
                "y":-600,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "x":-1200,
                "y":-120,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    -700,
                    -80
                ]
            },
            {
                "x":-1246.4680448000004,
                "y":-120.97231104,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    -700,
                    -80
                ]
            },
            {
                "x":-1247.05031168,
                "y":118.63951104,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    -700,
                    80
                ]
            },
            {
                "x":-1200,
                "y":120,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    -700,
                    80
                ]
            },
            {
                "x":1200,
                "y":-120,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    1200,
                    -120
                ]
            },
            {
                "x":1252.0639999999999,
                "y":-121.07999999999998,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    1200,
                    -120
                ]
            },
            {
                "x":1250.1632,
                "y":121.1664,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    1200,
                    120
                ]
            },
            {
                "x":1200,
                "y":120,
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"ffffff",
                "pos":[
                    1200,
                    120
                ]
            },
            {
                "x":-1200,
                "y":120,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff",
                "pos":[
                    -700,
                    80
                ]
            },
            {
                "x":-1200,
                "y":600,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff"
            },
            {
                "x":-1200,
                "y":-120,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff",
                "pos":[
                    -700,
                    -80
                ]
            },
            {
                "x":-1200,
                "y":-600,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff"
            },
            {
                "x":-1200,
                "y":600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff"
            },
            {
                "x":1200,
                "y":600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff"
            },
            {
                "x":1200,
                "y":120,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "pos":[
                    1200,
                    120
                ],
                "color":"ffffff"
            },
            {
                "x":1200,
                "y":600,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff"
            },
            {
                "x":1200,
                "y":-600,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff"
            },
            {
                "x":1200,
                "y":-120,
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "color":"ffffff",
                "pos":[
                    1200,
                    -120
                ]
            },
            {
                "x":-1200,
                "y":-600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "color":"ffffff"
            },
            {
                "x":1200,
                "y":-600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "pos":[
                    -700,
                    80
                ],
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":-600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "vis":false,
                "curve":0,
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":-120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "vis":false,
                "curve":0,
                "pos":[
                    -700,
                    -80
                ],
                "color":"ffffff"
            },
            {
                "x":1206.5,
                "y":-600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "vis":false,
                "curve":0,
                "color":"ffffff"
            },
            {
                "x":1206.5,
                "y":-120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "vis":false,
                "curve":0,
                "pos":[
                    1200,
                    -120
                ],
                "color":"ffffff"
            },
            {
                "x":1206.5,
                "y":120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "pos":[
                    1200,
                    120
                ],
                "color":"ffffff"
            },
            {
                "x":1206.5,
                "y":600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "color":"ffffff"
            },
            {
                "x":-1200,
                "y":-120,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"F80000"
            },
            {
                "x":-1200,
                "y":120,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"F80000"
            },
            {
                "x":1200,
                "y":-120,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"0000F8",
                "pos":[
                    1200,
                    -120
                ]
            },
            {
                "x":1200,
                "y":120,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"0000F8",
                "pos":[
                    1200,
                    120
                ]
            },
            {
                "x":-1200,
                "y":560,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":-93.241608812827
            },
            {
                "x":-740,
                "y":100,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":-93.241608812827
            },
            {
                "x":-1200,
                "y":-560,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":93.241608812827
            },
            {
                "x":-740,
                "y":-100,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":93.241608812827
            },
            {
                "x":1200,
                "y":560,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":93.241608812827
            },
            {
                "x":740,
                "y":100,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":93.241608812827
            },
            {
                "x":1200,
                "y":-560,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":-93.241608812827
            },
            {
                "x":740,
                "y":-100,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":-93.241608812827
            },
            {
                "x":740,
                "y":100,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":0
            },
            {
                "x":740,
                "y":-100,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":0
            },
            {
                "x":740,
                "y":1,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":740,
                "y":-1,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":740,
                "y":3,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":740,
                "y":-4,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":740,
                "y":4,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":-740,
                "y":1,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":-740,
                "y":-1,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":-740,
                "y":3,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":-740,
                "y":-4,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":-740,
                "y":4,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180,
                "color":"ffffff"
            },
            {
                "x":-1200,
                "y":120,
                "bCoef":0.2,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"a3acc2",
                "pos":[
                    -700,
                    80
                ],
                "vis":false
            },
            {
                "x":1200,
                "y":-120,
                "bCoef":0.2,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"a3acc2",
                "pos":[
                    1200,
                    -120
                ],
                "vis":false
            },
            {
                "x":1200,
                "y":120,
                "bCoef":0.2,
                "cMask":[
                    "red",
                    "blue",
                    "ball"
                ],
                "trait":"goalPost",
                "curve":0,
                "color":"a3acc2",
                "pos":[
                    1200,
                    120
                ],
                "vis":false
            },
            {
                "x":0,
                "y":600,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "x":0,
                "y":630,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "x":0,
                "y":120,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"696969",
                "curve":180
            },
            {
                "x":0,
                "y":-120,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"696969",
                "curve":180
            },
            {
                "x":0,
                "y":120,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"696969"
            },
            {
                "x":0,
                "y":-120,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"696969"
            },
            {
                "x":0,
                "y":-600,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":120,
                "cMask":[
                    
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":600,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "x":0,
                "y":120,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":600,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":120,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"ffffff",
                "curve":-93.241608812827
            },
            {
                "x":0,
                "y":-121,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180.5,
                "color":"ffffff"
            },
            {
                "x":0,
                "y":121,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "curve":180.5,
                "color":"ffffff"
            },
            {
                "x":0,
                "y":-121,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":-600,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":121,
                "bCoef":0,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":600,
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ],
                "color":"ffffff"
            },
            {
                "x":0,
                "y":121,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"a3acc2",
                "curve":-93.241608812827
            },
            {
                "x":0,
                "y":-121,
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "color":"a3acc2",
                "curve":93.241608812827
            },
            {
                "x":-1206.5,
                "y":120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "pos":[
                    -700,
                    80
                ],
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":-600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "vis":false,
                "curve":0,
                "color":"ffffff"
            },
            {
                "x":-1206.5,
                "y":-120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "vis":false,
                "curve":0,
                "pos":[
                    -700,
                    -80
                ],
                "color":"ffffff"
            },
            {
                "x":1206.5,
                "y":120,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "pos":[
                    1200,
                    120
                ],
                "color":"ffffff"
            },
            {
                "x":1206.5,
                "y":600,
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "curve":0,
                "vis":false,
                "color":"ffffff"
            },
            {
                "x":1235,
                "y":-630,
                "bCoef":0.5,
                "cMask":[
                    "red",
                    "blue"
                ],
                "color":"a3acc2"
            },
            {
                "x":1235,
                "y":630,
                "bCoef":0.5,
                "cMask":[
                    "red",
                    "blue"
                ],
                "color":"a3acc2"
            },
            {
                "x":-1235,
                "y":-630,
                "bCoef":0.5,
                "cMask":[
                    "red",
                    "blue"
                ],
                "color":"a3acc2"
            },
            {
                "x":-1235,
                "y":630,
                "bCoef":0.5,
                "cMask":[
                    "red",
                    "blue"
                ],
                "color":"a3acc2"
            },
            {
                "x":46,
                "y":88,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-46,
                "y":-20,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":52,
                "y":82,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":71,
                "y":66,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":18,
                "y":47,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-30,
                "y":50,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-37,
                "y":-59,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-34,
                "y":-11,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":4,
                "y":-11,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-37,
                "y":-105,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-20,
                "y":-100,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-29,
                "y":-87,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-19,
                "y":-67,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-43,
                "y":-71,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-5,
                "y":-32,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":6,
                "y":8,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":32,
                "y":-1,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":11,
                "y":-39,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":-10,
                "y":14,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":49,
                "y":-5,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":45,
                "y":12,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":9,
                "y":23,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "x":10,
                "y":-58,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":-90
            },
            {
                "x":8,
                "y":-79,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":-90
            },
            {
                "x":-3,
                "y":-112,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":60
            },
            {
                "x":-13,
                "y":-135,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":60
            },
            {
                "x":22,
                "y":-137,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":70
            },
            {
                "x":26,
                "y":-163,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "curve":70
            }
        ],
        "segments":[
            {
                "v0":0,
                "v1":1,
                "vis":false,
                "color":"F8F8F8",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":2,
                "v1":3,
                "curve":0,
                "color":"ffffff",
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "pos":[
                    -700,
                    -80
                ],
                "y":-120
            },
            {
                "v0":3,
                "v1":4,
                "curve":0.8741505747911814,
                "color":"ffffff",
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "x":-1235
            },
            {
                "v0":4,
                "v1":5,
                "curve":0,
                "color":"ffffff",
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "pos":[
                    -700,
                    80
                ],
                "y":120
            },
            {
                "v0":6,
                "v1":7,
                "curve":0,
                "color":"ffffff",
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "pos":[
                    1200,
                    -120
                ],
                "y":-120
            },
            {
                "v0":7,
                "v1":8,
                "curve":0,
                "color":"ffffff",
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "x":1235
            },
            {
                "v0":8,
                "v1":9,
                "curve":0,
                "color":"ffffff",
                "bCoef":0.2,
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ],
                "trait":"goalPost",
                "pos":[
                    1200,
                    120
                ],
                "y":120
            },
            {
                "v0":10,
                "v1":11,
                "vis":true,
                "color":"ffffff",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-550
            },
            {
                "v0":12,
                "v1":13,
                "vis":true,
                "color":"ffffff",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-550
            },
            {
                "v0":14,
                "v1":15,
                "vis":true,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "y":240
            },
            {
                "v0":16,
                "v1":17,
                "vis":true,
                "color":"ffffff",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":550
            },
            {
                "v0":18,
                "v1":19,
                "vis":true,
                "color":"ffffff",
                "bCoef":1.15,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":550
            },
            {
                "v0":20,
                "v1":21,
                "curve":0,
                "vis":true,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "y":-600
            },
            {
                "v0":22,
                "v1":23,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-556.5
            },
            {
                "v0":24,
                "v1":25,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-556.5
            },
            {
                "v0":26,
                "v1":27,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":556.5
            },
            {
                "v0":28,
                "v1":29,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":556.5
            },
            {
                "v0":30,
                "v1":31,
                "curve":0,
                "vis":true,
                "color":"F80000",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":-550
            },
            {
                "v0":32,
                "v1":33,
                "curve":0,
                "vis":true,
                "color":"0000F8",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":550
            },
            {
                "v0":34,
                "v1":35,
                "curve":-93.241608812827,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line"
            },
            {
                "v0":36,
                "v1":37,
                "curve":93.241608812827,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line"
            },
            {
                "v0":35,
                "v1":37,
                "curve":0,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":-740
            },
            {
                "v0":38,
                "v1":39,
                "curve":93.241608812827,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line"
            },
            {
                "v0":40,
                "v1":41,
                "curve":-93.241608812827,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line"
            },
            {
                "v0":42,
                "v1":43,
                "curve":0,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":740
            },
            {
                "v0":45,
                "v1":44,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":740
            },
            {
                "v0":44,
                "v1":45,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":740
            },
            {
                "v0":47,
                "v1":46,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":740
            },
            {
                "v0":46,
                "v1":47,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":740
            },
            {
                "v0":50,
                "v1":49,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":-740
            },
            {
                "v0":49,
                "v1":50,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":-740
            },
            {
                "v0":52,
                "v1":51,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":-740
            },
            {
                "v0":51,
                "v1":52,
                "curve":180,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":-740
            },
            {
                "v0":57,
                "v1":58,
                "vis":false,
                "color":"F8F8F8",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":59,
                "v1":60,
                "curve":180,
                "color":"696969",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "blueKO"
                ],
                "curveF":0.0049891420830909
            },
            {
                "v0":62,
                "v1":61,
                "curve":180,
                "color":"696969",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO"
                ],
                "curveF":6.1232339957368e-17
            },
            {
                "v0":70,
                "v1":69,
                "curve":180.5,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":0
            },
            {
                "v0":69,
                "v1":70,
                "curve":180.5,
                "vis":true,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "wall"
                ],
                "trait":"line",
                "x":0
            },
            {
                "v0":72,
                "v1":71,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":73,
                "v1":74,
                "color":"ffffff",
                "bCoef":0.1,
                "cMask":[
                    "red",
                    "blue"
                ],
                "cGroup":[
                    "redKO",
                    "blueKO"
                ]
            },
            {
                "v0":77,
                "v1":78,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-556.5
            },
            {
                "v0":79,
                "v1":80,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":-556.5
            },
            {
                "v0":81,
                "v1":82,
                "curve":0,
                "vis":false,
                "color":"ffffff",
                "bCoef":1,
                "cMask":[
                    "ball"
                ],
                "trait":"ballArea",
                "x":556.5
            },
            {
                "v0":87,
                "v1":88,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":89,
                "v1":90,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":89,
                "v1":91,
                "curve":-22.619864948040426,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":91,
                "v1":92,
                "curve":16.602608746122016,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":92,
                "v1":93,
                "curve":2.7710522090277254,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":94,
                "v1":95,
                "curve":-24.300337677524873,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":93,
                "v1":96,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":96,
                "v1":93,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":97,
                "v1":98,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":98,
                "v1":97,
                "curve":190,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":99,
                "v1":100,
                "curve":60,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":101,
                "v1":102,
                "curve":40,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":103,
                "v1":104,
                "curve":40,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":101,
                "v1":104,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":105,
                "v1":106,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":106,
                "v1":107,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":107,
                "v1":108,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":108,
                "v1":105,
                "color":"0080ff",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":109,
                "v1":110,
                "curve":-90,
                "color":"505050",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":111,
                "v1":112,
                "curve":60,
                "color":"505050",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            },
            {
                "v0":113,
                "v1":114,
                "curve":70,
                "color":"505050",
                "cMask":[
                    "wall"
                ],
                "cGroup":[
                    "wall"
                ]
            }
        ],
        "planes":[
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-630,
                "bCoef":0.1
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-600,
                "cMask":[
                    "ball"
                ]
            },
            {
                "normal":[
                    0,
                    -1
                ],
                "dist":-630,
                "bCoef":0.1
            },
            {
                "normal":[
                    0,
                    1
                ],
                "dist":-600,
                "cMask":[
                    "ball"
                ]
            }
        ],
        "goals":[
            {
                "p0":[
                    -1207.5,
                    -120
                ],
                "p1":[
                    -1207.5,
                    120
                ],
                "team":"red",
                "color":"ffffff"
            },
            {
                "p0":[
                    1207.5,
                    120
                ],
                "p1":[
                    1207.5,
                    -120
                ],
                "team":"blue",
                "color":"ffffff"
            }
        ],
        "discs":[
            {
                "radius":6,
                "invMass":0,
                "pos":[
                    -1200,
                    120
                ],
                "color":"ffffff",
                "trait":"goalPost",
                "y":85
            },
            {
                "radius":6,
                "invMass":0,
                "pos":[
                    -1200,
                    -120
                ],
                "color":"ffffff",
                "trait":"goalPost",
                "y":-110,
                "x":-560
            },
            {
                "radius":6,
                "invMass":0,
                "pos":[
                    1200,
                    120
                ],
                "color":"ffffff",
                "trait":"goalPost",
                "y":85
            },
            {
                "radius":6,
                "invMass":0,
                "pos":[
                    1200,
                    -120
                ],
                "color":"ffffff",
                "trait":"goalPost",
                "y":-110,
                "vis":true
            }
        ],
        "playerPhysics":{
            "bCoef":0.1,
            "acceleration":0.11,
            "kickingAcceleration":0.083,
            "kickStrength":4.9,
            "radius":15,
            "invMass":0.5,
            "damping":0.96,
            "cGroup":[
                "red",
                "blue"
            ],
            "gravity":[
                0,
                0
            ],
            "kickingDamping":0.96,
            "kickback":0
        },
        "ballPhysics":{
            "radius":6.25,
            "bCoef":0.4,
            "invMass":1.5,
            "color":"FEBA01",
            "cMask":[
                "all"
            ],
            "damping":0.99,
            "gravity":[
                0,
                0
            ],
            "cGroup":[
                "ball"
            ]
        },
        "spawnDistance":320,
        "traits":{
            
        },
        "joints":[
            
        ],
        "redSpawnPoints":[
            
        ],
        "blueSpawnPoints":[
            
        ],
        "cameraWidth":0,
        "cameraHeight":0,
        "maxViewWidth":0,
        "cameraFollow":"ball",
        "kickOffReset":"partial"
    }
    `
};

